# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

matrix:
  include:

  - r: devel

  - r: release
    before_cache:
    - Rscript -e 'remotes::install_cran("callr")'
    - Rscript -e 'install.packages("pkgdown")'
    after_success:
    - Rscript -e 'covr::codecov()'

  - r: 3.6
  - r: 3.5
  - r: 3.4
  - r: 3.3

addons:
  apt:
    packages:
    - python3-dev
    - python3-virtualenv
    - python3-venv
