# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

matrix:
  include:

  - r: devel

  - r: release
    before_cache:
    - Rscript -e 'remotes::install_github("r-lib/pkgdown", ref = "5f6ce0c2f503737c5d875657ab29234f6600aaae")'
    after_success:
    - Rscript -e 'covr::codecov(function_exclusions = c("stopf"))'
    deploy:
      provider: script
      script: Rscript -e 'print(.libPaths()); library(fansi); pkgdown::deploy_site_github()'
      skip_cleanup: true

  - r: oldrel
  - r: 3.4
  - r: 3.3
  - r: 3.2

addons:
  apt:
    packages:
    - python3-dev
    - python3-virtualenv
    - python3-venv
